#!/usr/bin/env sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
SELECT 'CREATE USER ${LITELLM_DB_USER} WITH PASSWORD ''${LITELLM_DB_PASSWORD}'''
WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${LITELLM_DB_USER}')\\gexec

SELECT 'CREATE DATABASE ${LITELLM_DB} OWNER ${LITELLM_DB_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${LITELLM_DB}')\\gexec

SQL
